<?php
/**
 * @file
 * CKEditor 5 inspector module code.
 */

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_inspector_library_info_alter(&$libraries, $module) {
  if ($module == 'ckeditor5') {
    $libraries['backdrop.ckeditor5']['dependencies'][] = array(
      'ckeditor5_inspector',
      'ckeditor5.inspector',
    );
  }
}

/**
 * Implements hook_library_info().
 */
function ckeditor5_inspector_library_info() {
  $path = backdrop_get_path('module', 'ckeditor5_inspector');
  $libraries['ckeditor5.inspector'] = array(
    'title' => 'CKEditor 5 inspector',
    'website' => 'https://github.com/ckeditor/ckeditor5-inspector',
    'version' => '4.1.0',
    'js' => array(
      $path . '/libraries/ckeditor5-inspector/build/inspector.js' => array(),
      $path . '/js/ckeditor-inspector.js' => array(),
    ),
  );
  return $libraries;
}
